import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  Brain, 
  Shield, 
  Zap, 
  Users, 
  Award, 
  CheckCircle, 
  Star,
  ArrowRight,
  Github,
  Globe,
  Sparkles,
  Mic,
  Video,
  Clock,
  Download,
  Upload
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

export const About = () => {
  const features = [
    {
      icon: <Brain className="h-8 w-8 text-blue-500" />,
      title: "AI-Powered Questions",
      description: "Get personalized interview questions generated by Llama 3 AI based on your resume and job requirements."
    },
    {
      icon: <Shield className="h-8 w-8 text-green-500" />,
      title: "Privacy First",
      description: "Everything runs locally on your machine. Your data never leaves your device - no internet required!"
    },
    {
      icon: <Mic className="h-8 w-8 text-purple-500" />,
      title: "Real-time Speech Recognition",
      description: "Practice with voice responses that appear instantly as you speak, just like a real interview."
    },
    {
      icon: <Zap className="h-8 w-8 text-yellow-500" />,
      title: "Instant Feedback",
      description: "Receive detailed performance analysis and improvement suggestions after each interview session."
    },
    {
      icon: <Clock className="h-8 w-8 text-orange-500" />,
      title: "Timed Sessions",
      description: "Practice with realistic time constraints and automatic session management."
    },
    {
      icon: <Download className="h-8 w-8 text-cyan-500" />,
      title: "Downloadable Reports",
      description: "Save your performance reports and track your progress over time."
    }
  ];

  const technologies = [
    { name: "React", color: "bg-blue-100 text-blue-800" },
    { name: "TypeScript", color: "bg-blue-100 text-blue-800" },
    { name: "Ollama", color: "bg-green-100 text-green-800" },
    { name: "Llama 3", color: "bg-purple-100 text-purple-800" },
    { name: "Firebase", color: "bg-yellow-100 text-yellow-800" },
    { name: "Tailwind CSS", color: "bg-cyan-100 text-cyan-800" },
    { name: "Framer Motion", color: "bg-pink-100 text-pink-800" },
    { name: "Web Speech API", color: "bg-indigo-100 text-indigo-800" }
  ];

  const stats = [
    { label: "AI Models", value: "Local Llama 3", icon: <Brain className="h-5 w-5" /> },
    { label: "Privacy Level", value: "100% Local", icon: <Shield className="h-5 w-5" /> },
    { label: "Interview Types", value: "Multiple", icon: <Users className="h-5 w-5" /> },
    { label: "Real-time Features", value: "Speech & Timer", icon: <Zap className="h-5 w-5" /> }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
      {/* Hero Section */}
      <section className="py-20 px-4 text-center">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <div className="flex justify-center mb-6">
              <div className="bg-gradient-to-r from-blue-500 to-purple-600 p-4 rounded-full">
                <Brain className="h-12 w-12 text-white" />
              </div>
            </div>
            
            <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-6">
              AI Mock Interview Assistant
            </h1>
            
            <p className="text-xl text-gray-600 mb-8 leading-relaxed">
              Practice interviews with confidence using local AI technology. 
              Get personalized questions, real-time feedback, and improve your interview skills 
              - all while keeping your data completely private.
            </p>

            <div className="flex flex-wrap justify-center gap-4 mb-8">
              {technologies.map((tech, index) => (
                <Badge key={index} className={tech.color}>
                  {tech.name}
                </Badge>
              ))}
            </div>

            <div className="flex justify-center gap-4">
              <Link to="/signin">
                <Button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-3 text-lg">
                  Start Practicing
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Button variant="outline" className="px-8 py-3 text-lg">
                <Github className="mr-2 h-5 w-5" />
                View Source
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <Card className="text-center p-6 hover:shadow-lg transition-shadow">
                  <div className="flex justify-center mb-3 text-blue-600">
                    {stat.icon}
                  </div>
                  <div className="text-2xl font-bold text-gray-800 mb-1">
                    {stat.value}
                  </div>
                  <div className="text-sm text-gray-600">
                    {stat.label}
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-800 mb-4">
              Powerful Features for Interview Success
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Everything you need to ace your next interview, powered by cutting-edge AI technology
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <Card className="p-6 h-full hover:shadow-xl transition-all duration-300 hover:-translate-y-2">
                  <CardContent className="p-0">
                    <div className="mb-4">
                      {feature.icon}
                    </div>
                    <h3 className="text-xl font-semibold text-gray-800 mb-3">
                      {feature.title}
                    </h3>
                    <p className="text-gray-600 leading-relaxed">
                      {feature.description}
                    </p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-800 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600">
              Get started in minutes with our simple 4-step process
            </p>
          </div>

          <div className="grid md:grid-cols-4 gap-8">
            {[
              {
                step: 1,
                title: "Upload Resume",
                description: "Upload your resume or enter job description",
                icon: <Upload className="h-8 w-8 text-blue-500" />
              },
              {
                step: 2,
                title: "AI Analysis",
                description: "Local AI analyzes your content and generates questions",
                icon: <Brain className="h-8 w-8 text-green-500" />
              },
              {
                step: 3,
                title: "Practice Interview",
                description: "Answer questions with voice or text responses",
                icon: <Mic className="h-8 w-8 text-purple-500" />
              },
              {
                step: 4,
                title: "Get Feedback",
                description: "Receive detailed analysis and improvement tips",
                icon: <Award className="h-8 w-8 text-orange-500" />
              }
            ].map((item, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                className="text-center"
              >
                <div className="bg-gradient-to-br from-blue-50 to-purple-50 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                  {item.icon}
                </div>
                <div className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center mx-auto mb-3 text-sm font-bold">
                  {item.step}
                </div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">
                  {item.title}
                </h3>
                <p className="text-gray-600">
                  {item.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Privacy & Security Section */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <div className="bg-green-50 border border-green-200 rounded-2xl p-8">
              <Shield className="h-16 w-16 text-green-600 mx-auto mb-6" />
              <h2 className="text-3xl font-bold text-gray-800 mb-4">
                Your Privacy is Our Priority
              </h2>
              <p className="text-lg text-gray-600 mb-6 leading-relaxed">
                Unlike other platforms, everything runs locally on your machine. 
                Your resume, interview responses, and feedback never leave your device. 
                No internet required, no data collection, complete privacy guaranteed.
              </p>
              <div className="flex justify-center gap-6 text-sm text-green-700">
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4" />
                  100% Local Processing
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4" />
                  No Data Collection
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4" />
                  Offline Capable
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h2 className="text-4xl font-bold mb-4">
              Ready to Ace Your Next Interview?
            </h2>
            <p className="text-xl mb-8 opacity-90">
              Join thousands of professionals who have improved their interview skills with our AI-powered platform.
            </p>
            <Link to="/signin">
              <Button className="bg-white text-blue-600 hover:bg-gray-100 px-8 py-4 text-lg font-semibold">
                <Sparkles className="mr-2 h-5 w-5" />
                Start Your Free Interview Practice
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
};