import { Link } from "react-router-dom";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { Button } from "./ui/button";
import { Calendar, Eye, RotateCw, Sparkles, Trash, Download } from "lucide-react";
import { Interview } from "@/types";
import { format } from "date-fns";
import { toast } from "sonner";
import { deleteDoc, doc, collection, query, where, getDocs } from "firebase/firestore";
import { db } from "@/config/firebase.config";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "./ui/tooltip";

interface InterviewPinProps {
  interview: Interview;
  onMockPage?: boolean;
}

export const InterviewPin = ({ interview, onMockPage }: InterviewPinProps) => {
  const handleDeleteInterview = async () => {
    try {
      if (interview.id) {
        await deleteDoc(doc(db, "interviews", interview.id));
        toast.success("Deleted!", { description: "Interview deleted successfully" });
      }
    } catch (error) {
      console.log(error);
      toast.error("Error", {
        description: "Something went wrong.. Please try again later",
      });
    }
  };

  const handleDownloadReport = async () => {
    try {
      if (!interview.id) return;
      
      // Fetch the interview report
      const reportsQuery = query(
        collection(db, "interviewReports"),
        where("interviewId", "==", interview.id)
      );
      const reportSnapshot = await getDocs(reportsQuery);
      
      if (reportSnapshot.empty) {
        toast.error("No report found", {
          description: "No feedback report found for this interview"
        });
        return;
      }

      const reportData = reportSnapshot.docs[0].data();
      
      // Create a formatted report
      const reportContent = `
INTERVIEW FEEDBACK REPORT
========================

Interview: ${interview.name || 'Unnamed Interview'}
Date: ${format(interview.createdAt.toDate(), "MMMM dd, yyyy")}
Type: ${interview.interviewType || 'Technical'}
Level: ${interview.depthLevel || 'Intermediate'}

OVERALL RATING: ${reportData.overallRating}/10

OVERALL FEEDBACK:
${reportData.overallFeedback || 'No overall feedback available'}

QUESTION-BY-QUESTION BREAKDOWN:
${reportData.questionFeedbacks?.map((q: any, i: number) => `
${i + 1}. ${q.question}
   Your Answer: ${q.userAnswer}
   Rating: ${q.rating}/10
   Feedback: ${q.feedback}
   Ideal Answer: ${q.idealAnswer}
`).join('\n') || 'No detailed feedback available'}

---
Generated by AI Mock Interview Assistant
Powered by Ollama (Local AI)
      `;

      // Create and download the file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Interview-Report-${interview.name?.replace(/[^a-zA-Z0-9]/g, '-') || 'Report'}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast.success("Report downloaded!", {
        description: "Your interview report has been saved to your downloads folder"
      });
    } catch (error) {
      console.error("Error downloading report:", error);
      toast.error("Download failed", {
        description: "Failed to download the report. Please try again."
      });
    }
  };

  return (
    <Alert className="bg-gray-50 border-gray-200 shadow-sm p-4 rounded-md">
      <div className="flex items-center justify-between w-full">
        <div className="flex items-start flex-col">
          <AlertTitle className="text-xl font-bold">{interview.name}</AlertTitle>
          <AlertDescription className="text-sm text-gray-500 mt-1">
            {interview.objective}
          </AlertDescription>
        </div>
        {!onMockPage && (
          <div className="flex items-center gap-2">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="icon"
                    className="h-8 w-8 text-blue-500"
                    onClick={handleDeleteInterview}
                  >
                    <Trash className="w-4 h-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Delete</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>

            {interview.feedbackGenerated ? (
              <>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="outline"
                        size="icon"
                        className="h-8 w-8 text-green-600 hover:bg-green-50"
                        onClick={handleDownloadReport}
                      >
                        <Download className="w-4 h-4" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Download Report</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Link to={`/generate/interview/${interview.id}/start`}>
                        <Button
                          variant="outline"
                          size="icon"
                          className="h-8 w-8 text-blue-500"
                        >
                          <RotateCw className="w-4 h-4" />
                        </Button>
                      </Link>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Retake Interview</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Link to={`/generate/feedback/${interview.id}`}>
                        <Button
                          variant="outline"
                          size="icon"
                          className="h-8 w-8 text-blue-500"
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                      </Link>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>View Feedback</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </>
            ) : (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Link to={`/generate/interview/${interview.id}`}>
                      <Button
                        variant="outline"
                        size="icon"
                        className="h-8 w-8 text-blue-500"
                      >
                        <Sparkles className="w-4 h-4" />
                      </Button>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent>
                      <p>Start Interview</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
          </div>
        )}
      </div>

      <div className="flex justify-between items-center mt-4 text-xs text-gray-500">
        <div className="flex items-center gap-1">
          <Calendar className="w-4 h-4" />
          <span>{format(interview.createdAt.toDate(), "MMMM dd, yyyy")}</span>
        </div>
        {!onMockPage && !interview.feedbackGenerated && (
          <Link to={`/generate/interview/${interview.id}/start`}>
            <Button size="sm" className="flex items-center gap-1 bg-blue-500">
              Start
              <Sparkles className="w-3 h-3" />
            </Button>
          </Link>
        )}
      </div>
    </Alert>
  );
};